Development
deniko1985/transportprmbot pull request #4
Opened 2022-08-02 10:45 UTC by deniko1985

2022-08-14 11:04 UTC, arseniy-kozlov requested changes
@deniko1985 Я прошел по сценарию с выбором избранного в основном меню и обработу избранного. Другие сценарии не смотрел, так как очень и очень много замечаний.

2022-08-14 11:04 UTC, arseniy-kozlov commented on data.py
> +from config import route_types_tree_collection, full_route_collection, \
@deniko1985 Что за документ config? Он добавлен в гитигнор, но используется тут. Не совсем понятно, что он из себя представляет. Если это данные, то тогда стоит, например, в ридми описать их структуру

2022-08-14 11:04 UTC, arseniy-kozlov commented on keyboard.py
> +BUS = 'Автобус'
@deniko1985 Давай переименуем файл, например, constants.py. Сейчас совершенно не понятно, почему этот файл называется keyboard.

2022-08-14 11:04 UTC, arseniy-kozlov commented on keyboard.py
> +keyboard_user_choice = [BUS,TRAMWAY, TAXI, FAVOURITES, HELP]
@deniko1985 Необходимо придерживаться единого стиля в именовании констант, если большими буквами через нижнее подчеркивание, то и тут так должно быть.

+ стоит переименвать переменную, если это меню первого уровня, то так и должно называться, например, MENU_MAIN

2022-08-14 11:04 UTC, arseniy-kozlov commented on keyboard.py
> +keyboard_choice_action = [TIMETABLE, MAPS]
+1, например, MENU_ROUTE

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +from config import dp, bot, user_collection
@deniko1985 Видимо там не только данные, тогда совсем странно, что он добавлен в игтигнор

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +    markup.add(*list_button)
@deniko1985 Почему бы сразу не добавлять здесь keyboard_user_choice, а не дублировать сначала его в новый массив?

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +    await Transport.user_choice_transport.set()
@deniko1985 Наименования статусов совершенно не отражают того, что происходит. Например, здесь было бы логичнее перейти в статус, что-то типа `main_menu`

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +        bus_favourites = user_favourites[0]
@deniko1985 Лучше, чтобы в `user_favourites` возвращался не массив, а dictionary, тогда здесь код будет с одной стороны более читабельный, а с другой меньше вероятности ошибиться в будущем, если появятся новые виды транспорта, например.

Не стоит использовать индекс массива для идентификации данных внутри массива. Если использовать массив здесь обязательно, то надо делать функцию, которая по типу будет находить элемент в массиве и использовать ее тут.

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +                list_button_favourites_taxi.append(inline_btn_favourites_taxi)
@deniko1985 Строки 62-65, 66-69 и 70-73 практически идентичны, уверен, что здесь можно оптимизировать код

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        user_clt = user_collection.find()
@deniko1985 Эта переменная нигде дальше не используется, зачем она здесь и зачем делается лишнее обращение к базе?

Еще раз что такое файл config, на него завязана половина логики работы бота, но он исключен из ревью

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +            print(cursor)
@deniko1985  Похоже забыл удалить отладочную печать

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +                print(i)
+1

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +                print(id_list)
+1

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +            user_collection.insert_one({'_id': user_id, 'chat_id': chat_id, 'bus': [], 'tramway': [], 'taxi': []})
@deniko1985 Нигде не описана модель данных, практически невозможно понять, какая структура данных ожидается внутри массиов bus, tramway и taxi

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        if transport == BUS:
@deniko1985 Было бы эффективнее хранить избранное в одном списке, сохраняя не только номер, но и тип транспорта. Стоит это переделать

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        user_collection.update_one({'_id': user_id}, {'$addToSet': {transport_add: route_number}})
@deniko1985 Не хватает проверки, что такой маршрут уже добавлен в избранное

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +    async def choice_favourites(user_id):
@deniko1985 Стоит переименовать метод в `get_user_favourites`

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        favourites_bus_list = [BUS, []]
@deniko1985 Почему тут решено использовать массив с разнотипными элементами? Стоит переделать на  dictionary

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        for favourites_route in user_collection.find({'_id': user_id}):
@deniko1985 Разве `user_collection.find` возвращает не массив пользователей по идентификатору, а его избранное?

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        favourites_list.append(favourites_taxi_list)
@deniko1985 Есть ощущение, что можно было бы не создавать лишние массивы, а возвращать данные из базы. Но я не понимаю код выше.

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +    async def check_favourites(user_id, choice_transport, choice_number):
@deniko1985 Плохое наименоваие параметров. Было бы логичнее использовать имена `transport_type` и `transport_number`, или даже лучше просто `type` и `number`

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        for favourites_route in user_collection.find({'_id': user_id}):
+1

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        for favourites_route in user_collection.find({'_id': user_id}):
@deniko1985 Я думаю, что здесь можно использовать https://www.mongodb.com/docs/manual/reference/method/db.collection.findOne/

2022-08-14 11:04 UTC, arseniy-kozlov commented on favourites.py
> +        if choice_number not in list_check_favourites:
+1

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +        print(user_favourites[0][1], user_favourites[1][1], user_favourites[2][1])
@deniko1985 Забыл удалить отладочную печать

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +        #await message.answer(text = 'Выбери номер маршрута', reply_markup=inline_kb_favourites)
@deniko1985 Забыл удалить неиспользуемый код

2022-08-14 11:04 UTC, arseniy-kozlov commented on main.py
> +        await Transport.next()
@deniko1985 Думаю, что стоит предерживаться единого подхода к обработке цепочек сообщений. Либо через смену состояния и отдельную обработку в завимости от состояния, либо вести пользователя по сообщениям, как тут. Чтобы не было мешанины. ЛУчше на мой взгляд через смену состояния.

2022-08-26 06:23 UTC, arseniy-kozlov commented on message_handler.py
> +        await UserState.MAIN_STATE.set()
@deniko1985 Здесь не надо менять состояние, так как ты это уже делаешь в `go_to_main_state`, который вызывается в следующей строке

2022-08-26 06:32 UTC, deniko1985 commented on message_handler.py
> +        await UserState.MAIN_STATE.set()
А, получается, что нигде при возврате не надо менять состояние?

2022-08-26 06:39 UTC, arseniy-kozlov commented on message_handler.py
> +        await UserState.MAIN_STATE.set()
Не надо, ты же меняешь его внутри `go_to_main_state`

2022-08-26 06:42 UTC, arseniy-kozlov commented on message_handler.py
> +            await go_to_favourites_state(message, state)
@deniko1985 Не помню, чтобы на схеме состояний был переход из ROUTES_STATE в FAVOURITES_STATE. Если его не было, то откуда он тут появился?

2022-08-26 06:42 UTC, arseniy-kozlov commented on message_handler.py
> +            await UserState.FAVOURITES_STATE.set()
@deniko1985 И здесь, а дальше, не надо менять state, он должен меняться только внутри функций `go_to_...`

2022-08-26 06:44 UTC, arseniy-kozlov commented on message_handler.py
> +async def go_to_favourites_state(message: types.Message, state: FSMContext):
@deniko1985 Эта функция работает не на основе схемы состояний, вообще не вписывается в отсальную реализацию.

2022-08-26 12:36 UTC, arseniy-kozlov commented on favourites/favourites.py
> +        user_clt = USER_COLLECTION.find()
@deniko1985  Переменная, которая грузит базу, но не используется

2022-08-26 12:38 UTC, arseniy-kozlov commented on favourites/favourites.py
> +        for cursor in USER_COLLECTION.find({}, {'_id': 1}):
@deniko1985  Зачем создавать массив из идентификаторов всех пользователей и потом проверять вхождение user_id в этот массив, если можно просто найти пользователя с необходимым тебе идентификатором, используя эту же функцию find или findOne?

2022-08-26 12:40 UTC, arseniy-kozlov commented on favourites/favourites.py
> +        transport_add = ''
@deniko1985 Зачем вводить еще одну переменную, которая по итогам равна значению переменной transport?

2022-08-26 13:16 UTC, deniko1985 commented on favourites/favourites.py
> +        transport_add = ''
Она не равно значению переменной transport. Значение переменной transport константы BUS, TRAMWAY или TAXI, данным константам присвоены значения 'Автобус', 'Трамвай', 'Маршрутное такси' соответственно. А переменной transport_add присваиваются строки 'bus', 'tramway', 'taxi' и они не равны строкам выше. А данные строки это ключи полей в документе БД.

2022-08-26 13:16 UTC, deniko1985 commented on favourites/favourites.py
> +        user_clt = USER_COLLECTION.find()
Удалил, она осталась с какого-то старого кода.

2022-08-26 13:18 UTC, deniko1985 commented on favourites/favourites.py
> +        for cursor in USER_COLLECTION.find({}, {'_id': 1}):
Потому что, если идентификатора нет, то выпадает ошибка.

2023-03-06 17:29 UTC, closed without merging